---
abstract: 'A Task module for DWIM Perl L<http://dwimperl.com/>'
author:
  - 'Gabor Szabo <szabgab@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Perl::Version: 1.011
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-DWIM-Email
no_index:
  directory:
    - inc
    - t
requires:
  Email::Abstract: 3.004
  Email::Address: 1.895
  Email::Date::Format: 1.002
  Email::MIME: 1.910
  Email::MIME::ContentType: 1.015
  Email::MIME::Encodings: 1.313
  Email::MIME::Kit: 2.102010
  Email::MessageID: 1.402
  Email::Sender: 0.110003
  Email::Simple: 2.101
  Email::Valid: 0.187
  MIME::Lite: 3.028
  Mail::Address: 2.08
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/dwimperl/Task-DWIM
version: 0.07
